import React from "react";
const Details=(props)=>{
    return(

        <>
        <div>
           <h1>{props.data[0].name}</h1> 
            <h1>{props.data[0].branch}</h1>
            <h1>{props.data[0].usn}</h1>
            <h1>{props.data[1].name}</h1> 
            <h1>{props.data[1].branch}</h1>
            <h1>{props.data[1].usn}</h1>
            <h1>{props.data[2].name}</h1> 
            <h1>{props.data[2].branch}</h1>
            <h1>{props.data[2].usn}</h1>
            <h1>{props.data[3].name}</h1> 
            <h1>{props.data[3].branch}</h1>
            <h1>{props.data[4].usn}</h1>
            <h1>{props.data[4].name}</h1> 
            <h1>{props.data[4].branch}</h1>
            <h1>{props.data[5].usn}</h1>
            <h1>{props.data[5].name}</h1> 
            <h1>{props.data[5].branch}</h1>
            <h1>{props.data[6].usn}</h1>
            <h1>{props.data[6].name}</h1> 
            <h1>{props.data[6].branch}</h1>
            <h1>{props.data[7].usn}</h1>
            <h1>{props.data[7].name}</h1> 
            <h1>{props.data[7].branch}</h1>
            <h1>{props.data[8].usn}</h1>
            <h1>{props.data[8].name}</h1> 
            <h1>{props.data[8].branch}</h1>
            <h1>{props.data[9].usn}</h1>
            <h1>{props.data[9].name}</h1> 
            <h1>{props.data[9].branch}</h1>
            <h1>{props.data[10].usn}</h1>
            <h1>{props.data[10].name}</h1> 
            <h1>{props.data[10].branch}</h1>
            <h1>{props.data[11].usn}</h1>
            <h1>{props.data[11].name}</h1> 
            <h1>{props.data[11].branch}</h1>
            <h1>{props.data[12].usn}</h1>
            <h1>{props.data[12].name}</h1> 
            <h1>{props.data[12].branch}</h1>
            <h1>{props.data[13].usn}</h1>
            <h1>{props.data[13].name}</h1> 
            <h>{props.data[13].branch}</h>
            <h1>{props.data[14].usn}</h1>
            <h1>{props.data[14].name}</h1> 
            <h1>{props.data[14].branch}</h1>
            <h1>{props.data[15].usn}</h1>
            <h1>{props.data[15].name}</h1> 
            <h1>{props.data[15].branch}</h1>
            <h1>{props.data[16].usn}</h1>
            <h1>{props.data[16].name}</h1> 
            <h1>{props.data[16].branch}</h1>
            <h1>{props.data[17].usn}</h1>
            <h1>{props.data[17].name}</h1> 
            <h1>{props.data[17].branch}</h1>
            <h1>{props.data[18].usn}</h1>
            <h1>{props.data[18].name}</h1> 
            <h1>{props.data[18].branch}</h1>
            <h1>{props.data[19].usn}</h1>
            <h1>{props.data[19].name}</h1> 
            <h1>{props.data[19].branch}</h1>
            <h1>{props.data[20].usn}</h1>
            <h1>{props.data[20].name}</h1> 
            <h1>{props.data[20].branch}</h1>
        </div>
        </>
    )
}
export default Details